version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - HOST=web
      - PORT=8000
      - SPRING_API_PORT=8080
      - NETWORK=localarea
    expose:
      - "8000"
    networks:
      - localarea
    depends_on:
      - kotlin_server

  kotlin_server:
    image: prendota/kotlin-compiler-server
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - ACCESS_CONTROL_ALLOW_ORIGIN_VALUE=*
    networks:
      localarea:
        aliases:
          - localarea

networks:
  localarea:
    driver: bridge
