services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        environment:
            - PORT=8000
            - CONN=pyserver
            - CONN_PORT=8002
            - SPRING_API_PORT=8080
            - NETWORK=kotlin_server
        expose:
          - "8000"
        networks:
            - localarea
        depends_on:
            - kotlin_server

    kotlin_server:
        image: prendota/kotlin-compiler-server
        ports:
            - "8080:8080"
        environment:
            - ACCESS_CONTROL_ALLOW_ORIGIN_VALUE=*
        expose:
            - "8080"
        networks:
            - localarea

networks:
    localarea:
        driver: bridge